//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.24 at 01:00:07 PM GMT 
//


package uk.ac.ebi.mydas.examples.solr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for add complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="add">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="doc" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="field" type="{http://schema.epublishing.com/solr}field" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="boost" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="allowDups" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="overwritePending" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="overwriteCommitted" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "add", propOrder = {
    "doc"
})
public class Add {

    @XmlElement(required = true)
    protected List<Add.Doc> doc;
    @XmlAttribute(name = "allowDups")
    protected Boolean allowDups;
    @XmlAttribute(name = "overwritePending")
    protected Boolean overwritePending;
    @XmlAttribute(name = "overwriteCommitted")
    protected Boolean overwriteCommitted;

    /**
     * Gets the value of the doc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Add.Doc }
     * 
     * 
     */
    public List<Add.Doc> getDoc() {
        if (doc == null) {
            doc = new ArrayList<Add.Doc>();
        }
        return this.doc;
    }

    /**
     * Gets the value of the allowDups property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowDups() {
        return allowDups;
    }

    /**
     * Sets the value of the allowDups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowDups(Boolean value) {
        this.allowDups = value;
    }

    /**
     * Gets the value of the overwritePending property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverwritePending() {
        return overwritePending;
    }

    /**
     * Sets the value of the overwritePending property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverwritePending(Boolean value) {
        this.overwritePending = value;
    }

    /**
     * Gets the value of the overwriteCommitted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverwriteCommitted() {
        return overwriteCommitted;
    }

    /**
     * Sets the value of the overwriteCommitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverwriteCommitted(Boolean value) {
        this.overwriteCommitted = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="field" type="{http://schema.epublishing.com/solr}field" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="boost" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class Doc {

        @XmlElement(required = true)
        protected List<Field> field;
        @XmlAttribute(name = "boost")
        protected java.lang.Float boost;

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Field }
         * 
         * 
         */
        public List<Field> getField() {
            if (field == null) {
                field = new ArrayList<Field>();
            }
            return this.field;
        }

        /**
         * Gets the value of the boost property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Float }
         *     
         */
        public java.lang.Float getBoost() {
            return boost;
        }

        /**
         * Sets the value of the boost property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Float }
         *     
         */
        public void setBoost(java.lang.Float value) {
            this.boost = value;
        }

    }

}
