//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2.1.1-4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.24 at 01:00:07 PM GMT 
//


package uk.ac.ebi.mydas.examples.solr;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for arr complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="arr">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="str" type="{http://schema.epublishing.com/solr}str"/>
 *           &lt;element name="int" type="{http://schema.epublishing.com/solr}int"/>
 *           &lt;element name="float" type="{http://schema.epublishing.com/solr}float"/>
 *           &lt;element name="bool" type="{http://schema.epublishing.com/solr}bool"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "arr", propOrder = {
    "strOrIntOrFloat"
})
public class Arr {

    @XmlElements({
        @XmlElement(name = "str", type = Str.class),
        @XmlElement(name = "bool", type = Bool.class),
        @XmlElement(name = "float", type = Float.class),
        @XmlElement(name = "int", type = Int.class)
    })
    protected List<Object> strOrIntOrFloat;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the strOrIntOrFloat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strOrIntOrFloat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrOrIntOrFloat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Str }
     * {@link Bool }
     * {@link Float }
     * {@link Int }
     * 
     * 
     */
    public List<Object> getStrOrIntOrFloat() {
        if (strOrIntOrFloat == null) {
            strOrIntOrFloat = new ArrayList<Object>();
        }
        return this.strOrIntOrFloat;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
